name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Deploying to EC2 instance
      env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.EC2_HOST}}
          USER_NAME: ${{secrets.EC2_USER}}

      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          ls -l
        '
