name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploying to EC2 instance
      env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.EC2_HOST}}
          USER_NAME: ${{secrets.EC2_USER}}

      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash. ~/.nvm/nvm.sh
          . ~/.nvm/nvm.sh
          nvm install --lts
          rm -rf /tmp/projects
          mkdir /tmp/projects
          cd /tmp/projects
          git clone https://github.com/AyuAyushi/nodejs-hello-world.git
          cd nodejs-hello-world
          git pull origin main
          npm install
          pm2 stop index.js || true
          pm2 start index.js
        '
    - name: Notify deployment success
      run: echo "Deployment successful"
